Test PR
MrYar0s/VYStat-VM pull request #7
Opened 2023-11-19 10:56 UTC by MrYar0s

DO NOT MERGE!

2023-11-29 13:54 UTC, MrYar0s commented
NOTE: Rewriting parameters for vm now

2023-11-30 23:08 UTC, VasiliyMatr requested changes
Looks fine. Consider my suggestions

2023-11-30 23:08 UTC, VasiliyMatr commented on assembler/gen_instr.py
> +            "// According to clang-tidy errors\n"
Virtual destructor is actually needed. Remove comment?

2023-11-30 23:08 UTC, VasiliyMatr commented on common/include/shrimp/common/logger.hpp
> +enum LogLevel : uint8_t { NONE = 0, ERROR, INFO, DEBUG };
Enum class?

2023-11-30 23:08 UTC, VasiliyMatr commented on runtime/shrimp_vm/include/shrimp/runtime/shrimp_vm.hpp
> +    LogLevel getLogLevel()
```suggestion
    [[nodiscard]] auto getLogLevel() const noexcept
```

2023-11-30 23:08 UTC, VasiliyMatr commented on runtime/shrimp_vm/include/shrimp/runtime/shrimp_vm.hpp
> +    LogLevel log_level_;
```suggestion
    LogLevel log_level_ = LogLevel::NONE;
```

2023-11-30 23:08 UTC, VasiliyMatr commented on scripts/run_clang_tidy.py
> +PROGRAM = "clang-tidy"
Maybe just write "clang-tidy"?

2023-11-30 23:08 UTC, VasiliyMatr commented on shrimp/src/shrimp.cpp
> +LogLevel getLogLevel(int argc, char *argv[])
Remove?

2023-11-30 23:08 UTC, VasiliyMatr commented on shrimp/src/shrimp.cpp
>  std::string getFileName(int argc, char *argv[])
Remove?

2023-11-30 23:08 UTC, VasiliyMatr commented on shrimp/src/shrimp.cpp
> +    auto *log_level_cli = app.add_option("--log-level", log_level_str, "Log level file [error, info, debug, none]");
```suggestion
    auto *log_level_cli = app.add_option("--log-level", log_level_str, "Log level [error, info, debug, none]");
```

2023-11-30 23:08 UTC, VasiliyMatr commented on shrimp/src/shrimp.cpp
> +    auto *input_arg = app.add_option("--in", input_file, "Input file [Required as last parameter]");
```suggestion
    auto *input_arg = app.add_option("--in", input_file, "Input file");
```

2023-11-30 23:08 UTC, VasiliyMatr commented on shrimp/src/shrimp.cpp
>      auto native_code = readFromFile(file_name);
```suggestion
    auto native_code = readFromFile(input_file);
```

2023-11-30 23:08 UTC, VasiliyMatr commented on shrimp/src/shrimp.cpp
>      std::string file_name = getFileName(argc, argv);
```suggestion
```

2023-11-30 23:08 UTC, VasiliyMatr commented on shrimp/src/shrimp.cpp
>      return svm.runImpl();
Maybe print status?

2023-11-30 23:08 UTC, VasiliyMatr commented on tests/cts_tests/interpreter/CMakeLists.txt
>  		DEPENDS assembler
```suggestion
		DEPENDS assembler ${TEST_SOURCE_PATH}
```

2023-11-30 23:08 UTC, VasiliyMatr commented on tests/e2e_tests/CMakeLists.txt
>  		DEPENDS assembler
```suggestion
		DEPENDS assembler ${TEST_SOURCE_PATH}
```

2023-12-05 10:16 UTC, merged